import type { ControlsState } from "../types/pipeline";

export type KeysMatching<T, Value> = {
  [Key in keyof T]-?: T[Key] extends Value ? Key : never;
}[keyof T];

export type NumericControlField = KeysMatching<ControlsState, number>;

export const numericFields: NumericControlField[] = [
  "transparentThreshold",
  "opaqueThreshold",
  "edgeSoftness",
  "edgeBlurSigma",
  "despillStrength",
  "despillAlphaStrength",
  "neutralizeStrength",
  "edgeDarken",
  "outlineWidth",
  "outlineOpacity",
  "outlineBlur",
  "alphaCleanupMinArea",
  "alphaCleanupCloseSize",
  "cropPadding",
  "framePadding",
  "minFrameArea",
  "alphaCutoff",
  "flowDeflickerStrength",
  "flowDeflickerRadius",
  "flowColorTolerance",
  "flowAlphaTolerance",
  "flowConsistencyTolerance",
  "flowMaxDisplacement",
  "flowConfidenceFloor",
  "temporalDeflickerStrength",
  "temporalStaticCoverage",
  "temporalColorTolerance",
  "temporalAlphaTolerance",
  "sheetExtrudePixels",
  "semanticGroundingMinConfidence",
  "semanticGroundingAlphaCutoff",
  "semanticGroundingDilationRadius",
  "semanticGroundingFrameMinScore",
  "semanticGroundingExpandRatio",
  "semanticGroundingExpandMinPx",
  "partRepairSearchScale",
  "partPatchLockStrength",
  "partMedianStrength",
];

export function isNumericControlField(field: keyof ControlsState): field is NumericControlField {
  return numericFields.includes(field as NumericControlField);
}

export const defaultControls: ControlsState = {
  source: "",
  profile: "auto",
  pipelineId: "greenscreen-clean",
  transparentThreshold: 26,
  opaqueThreshold: 150,
  edgeSoftness: 2.6,
  edgeBlurSigma: 0.5,
  despillStrength: 0.9,
  despillAlphaMode: "preserve",
  despillAlphaStrength: 0.75,
  neutralizeEdges: "auto",
  neutralizeStrength: 0.58,
  edgeDarken: 0.12,
  outlineWidth: 0,
  outlineOpacity: 0.78,
  outlineBlur: 0.6,
  alphaCleanupMinArea: 24,
  alphaCleanupCloseSize: 0,
  cropPadding: 12,
  framePadding: 18,
  minFrameArea: 1800,
  alphaCutoff: 10,
  flowDeflickerStrength: 0.55,
  flowDeflickerRadius: 1,
  flowColorTolerance: 34,
  flowAlphaTolerance: 58,
  flowConsistencyTolerance: 2.8,
  flowMaxDisplacement: 42,
  flowConfidenceFloor: 0.4,
  temporalDeflickerStrength: 0.45,
  temporalStaticCoverage: 0.68,
  temporalColorTolerance: 18,
  temporalAlphaTolerance: 38,
  sheetExtrudePixels: 2,
  upscaleMode: "none",
  pipelineStages: {},
  semanticManualParts: [],
  semanticEdits: [],
  semanticEditorParts: [],
  semanticEditTool: "positive_point",
  semanticInputMode: "neutral_matte",
  semanticGroundingMinConfidence: 0.35,
  semanticGroundingAlphaCutoff: 10,
  semanticGroundingDilationRadius: 2,
  semanticGroundingAllowFrameReassign: true,
  semanticGroundingFrameMinScore: 0.08,
  semanticGroundingProjectionMode: "by_persistence",
  semanticGroundingExpandRatio: 0.08,
  semanticGroundingExpandMinPx: 2,
  semanticGroundingEmitBbox: true,
  semanticGroundingEmitPositivePoint: true,
  semanticMaskModel: "sam3",
  partStabilizeEnabled: true,
  partRepairEnabled: true,
  partRepairSearchScale: 1,
  partPatchLockStrength: 1,
  partMedianStrength: 1,
  exportSlug: "sprite-workbench",
};

export const RANGE_CONFIG: Partial<Record<string, [string, number, number, number]>> = {
  transparentThreshold: ["Transparent threshold", 0, 90, 1],
  opaqueThreshold: ["Opaque threshold", 32, 255, 1],
  edgeSoftness: ["Edge softness", 0.5, 6, 0.1],
  edgeBlurSigma: ["Edge blur sigma", 0, 3, 0.05],
  alphaCutoff: ["Alpha cutoff", 0, 64, 1],
  despillStrength: ["Despill strength", 0, 1.6, 0.05],
  despillAlphaStrength: ["Spill alpha cut", 0, 2.4, 0.05],
  neutralizeStrength: ["Neutralize strength", 0, 1.4, 0.05],
  edgeDarken: ["Edge darken", 0, 0.8, 0.02],
  outlineWidth: ["Outline width", 0, 6, 1],
  outlineOpacity: ["Outline opacity", 0, 1, 0.05],
  outlineBlur: ["Outline blur", 0, 3, 0.05],
  alphaCleanupMinArea: ["Alpha min area", 0, 300, 1],
  alphaCleanupCloseSize: ["Alpha close size", 0, 7, 1],
  cropPadding: ["Crop padding", 0, 64, 1],
  framePadding: ["Frame padding", 0, 64, 1],
  minFrameArea: ["Min frame area", 200, 12000, 50],
  flowDeflickerStrength: ["Flow strength", 0, 1, 0.05],
  flowDeflickerRadius: ["Flow radius", 1, 3, 1],
  flowColorTolerance: ["Flow color tol", 1, 96, 1],
  flowAlphaTolerance: ["Flow alpha tol", 1, 128, 1],
  flowConsistencyTolerance: ["Flow consistency", 0.5, 8, 0.1],
  flowMaxDisplacement: ["Flow max px", 4, 96, 1],
  flowConfidenceFloor: ["Flow floor", 0, 1, 0.05],
  temporalDeflickerStrength: ["Deflicker strength", 0, 1, 0.05],
  temporalStaticCoverage: ["Static coverage", 0.4, 1, 0.02],
  temporalColorTolerance: ["Color tolerance", 0, 64, 1],
  temporalAlphaTolerance: ["Alpha tolerance", 0, 96, 1],
  sheetExtrudePixels: ["Extrude pixels", 0, 8, 1],
  semanticGroundingMinConfidence: ["Min confidence", 0, 1, 0.01],
  semanticGroundingAlphaCutoff: ["Alpha cutoff", 0, 255, 1],
  semanticGroundingDilationRadius: ["Alpha dilation px", 0, 12, 1],
  semanticGroundingFrameMinScore: ["Frame min score", 0, 1, 0.01],
  semanticGroundingExpandRatio: ["BBox expand ratio", 0, 1, 0.01],
  semanticGroundingExpandMinPx: ["BBox expand min px", 0, 64, 1],
  partRepairSearchScale: ["Repair search", 0.1, 3, 0.05],
  partPatchLockStrength: ["Patch lock", 0, 1.5, 0.05],
  partMedianStrength: ["Median blend", 0, 1.5, 0.05],
};
